name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Plan, Scan & Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      TF_INPUT: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #############################################
      # Setup Terraform
      #############################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      #############################################
      # Security Scanning - tfsec
      #############################################
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      #############################################
      # Security Scanning - Checkov
      #############################################
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true

      #############################################
      # (Optional) Terrascan
      #############################################
      # - name: Run Terrascan
      #   uses: tenable/terrascan-action@main
      #   with:
      #     iac_type: terraform
      #     iac_version: v14
      #     policy_type: aws

      #############################################
      # Infracost - Cost Estimation
      #############################################
      - name: Setup Infracost
        uses: infracost/actions/setup@v2

      - name: Generate Infracost cost estimate
        run: |
          infracost breakdown --path=. \
            --format=json \
            --out-file=/tmp/infracost.json \
            --project-name=terraform-infra
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Show cost estimate
        run: |
          infracost output --path=/tmp/infracost.json --format=table
